name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests & Build
        run: mvn clean verify

      - name: SonarCloud Analysis
        run: mvn sonar:sonar
          -Dsonar.projectKey=rKrishan99_csci44092-order-service
          -Dsonar.organization=rkrishan99
          -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.5dbf416b323acbc90f5fc5ea710ff4b44b0bd779 }}